[env]
  NATS_USER = "sys"
  NATS_PASSWORD = "sys"

[experimental]
  private_network = true

[metrics]
  path = "/metrics"
  port = 7777

[[services]]
  internal_port = 7777
  protocol = "tcp"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
