# config file version
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: 'https://api.fly.io/prometheus/personal'
  isDefault: true
  version: 1
  editable: false
  jsonData:
      httpHeaderName1: 'Authorization'
  secureJsonData:
      httpHeaderValue1: 'Bearer $PROMETHEUS_API_TOKEN'
